apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.database.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.database.password | quote }}