apiVersion: v1
kind: ConfigMap

metadata:
  name: ezbookkeeping-config-file
  namespace: ezbookkeeping

data:
  ezbookkeeping.ini: |
    [Database]
    Type=postgres
    Host=postgres
    Port=5432
    Database=ezbookkeeping
    Username=ezuser
    Password=password123

    # Paste the remaining contents of your ezbookkeeping.ini here
