apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: ezbookkeeping

type: Opaque

stringData:
  POSTGRES_DB: ezbookkeeping
  POSTGRES_USER: ezuser
  POSTGRES_PASSWORD: password123
