apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}

spec:
  type: {{ .Values.postgres.service.type }}

  selector:
    app: postgres

  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.targetPort }}