apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: app-data-pvc
  namespace: ezbookkeeping

spec:
  storageClassName: gp2
  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
