apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: postgres-pvc
  namespace: ezbookkeeping

spec:
  #storageClassName: local-path
  storageClassName: gp2

  accessModes:
  - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
